# importing library and data set

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('cars.csv')

# multiple linear regression

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,2,5,6,7])],remainder='passthrough')


In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
print(x)

[[0.0e+00 0.0e+00 0.0e+00 ... 1.5e+03 1.1e+02 5.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.6e+03 1.4e+02 5.0e+00]
 [0.0e+00 0.0e+00 1.0e+00 ... 5.0e+03 4.0e+02 4.0e+00]
 ...
 [0.0e+00 0.0e+00 1.0e+00 ... 1.5e+03 1.2e+02 5.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.5e+03 1.1e+02 5.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.2e+03 8.5e+01 5.0e+00]]


In [ ]:
x=ct.fit_transform(x)


In [ ]:
x=x.toarray()

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
print(x_train.shape[0])

80


In [ ]:
print(x_test.shape[0])

20


In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_hat=lr.predict(x_test)


In [ ]:
y_hat2=lr.predict(x_train)

In [ ]:
print(y_hat.shape[0])

20


In [ ]:
print(y_test.shape[0])

20


In [ ]:
print(np.concatenate((y_hat2.reshape(len(y_hat2),1),(y_train.reshape(len(y_train),1))),1))

[[ 700000.  700000.]
 [1200000. 1200000.]
 [ 600000.  600000.]
 [ 700000.  700000.]
 [1600000. 1600000.]
 [2400000. 2400000.]
 [ 900000.  900000.]
 [ 600000.  600000.]
 [ 850000.  850000.]
 [4000000. 4000000.]
 [ 850000.  850000.]
 [ 500000.  500000.]
 [ 500000.  500000.]
 [ 600000.  600000.]
 [ 550000.  550000.]
 [2800000. 2800000.]
 [3000000. 3000000.]
 [2800000. 2800000.]
 [1600000. 1600000.]
 [2000000. 2000000.]
 [1000000. 1000000.]
 [ 600000.  600000.]
 [ 500000.  500000.]
 [ 450000.  450000.]
 [ 850000.  850000.]
 [ 650000.  650000.]
 [1900000. 1900000.]
 [1500000. 1500000.]
 [4000000. 4000000.]
 [ 750000.  750000.]
 [ 700000.  700000.]
 [ 750000.  750000.]
 [ 800000.  800000.]
 [ 750000.  750000.]
 [2700000. 2700000.]
 [2700000. 2700000.]
 [2000000. 2000000.]
 [ 500000.  500000.]
 [ 600000.  600000.]
 [ 500000.  500000.]
 [2300000. 2300000.]
 [ 800000.  800000.]
 [2700000. 2700000.]
 [2900000. 2900000.]
 [ 450000.  450000.]
 [3200000. 3200000.]
 [1300000. 1300000.]
 [3000000. 30

In [ ]:
np.set_printoptions(1)
print(np.concatenate((y_hat.reshape(len(y_hat),1),(y_test.reshape(len(y_test),1))),1))

[[3200000.  3200000. ]
 [2400000.  2400000. ]
 [2976794.7 2500000. ]
 [2689122.1 2600000. ]
 [3500000.  3500000. ]
 [2689122.1 2600000. ]
 [1580057.9 1800000. ]
 [ 500000.   500000. ]
 [ 476632.8  650000. ]
 [2900000.  2900000. ]
 [ 700000.   700000. ]
 [ 476632.8  650000. ]
 [1500000.  1500000. ]
 [1803483.9 1600000. ]
 [ 666963.2  650000. ]
 [ 600000.   600000. ]
 [1031624.8  850000. ]
 [1200000.  1200000. ]
 [ 700000.   700000. ]
 [2649023.3 2200000. ]]


In [ ]:
from sklearn.metrics import r2_score,mean_squared_error
print(r2_score(y_test,y_hat))

0.9667641223937208


In [ ]:
print(r2_score(y_train,lr.predict(x_train)))

1.0
