# importing library and data set

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('cars.csv')

# polynomial regression

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,2,5,6,7])],remainder='passthrough')


In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
x=ct.fit_transform(x)

In [ ]:
x=x.toarray()

In [ ]:
print(x)

[[0.0e+00 0.0e+00 0.0e+00 ... 1.5e+03 1.1e+02 5.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.6e+03 1.4e+02 5.0e+00]
 [0.0e+00 0.0e+00 1.0e+00 ... 5.0e+03 4.0e+02 4.0e+00]
 ...
 [0.0e+00 0.0e+00 1.0e+00 ... 1.5e+03 1.2e+02 5.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.5e+03 1.1e+02 5.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.2e+03 8.5e+01 5.0e+00]]


In [ ]:
print(x.shape[1])

83


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=4)
xtrain_poly=poly.fit_transform(x_train)
xtest_poly=poly.fit_transform(x_test)


In [ ]:
print(xtrain_poly.shape[0])

80


In [ ]:
print(xtest_poly.shape[0])

20


In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(xtrain_poly,y_train)


LinearRegression()

In [ ]:
y_hat=lr.predict(xtest_poly)

In [ ]:
np.set_printoptions(1)
print(np.concatenate((y_hat.reshape(len(y_hat),1),y_test.reshape(len(y_test),1)),1))

[[ 3199990.9  3200000. ]
 [ 2400001.5  2400000. ]
 [-2336766.8  2500000. ]
 [ 2702953.8  2600000. ]
 [ 3499986.9  3500000. ]
 [ 2702956.5  2600000. ]
 [ 1481982.7  1800000. ]
 [  500000.7   500000. ]
 [  128891.7   650000. ]
 [ 2900006.4  2900000. ]
 [  700003.2   700000. ]
 [  128890.7   650000. ]
 [ 1499997.   1500000. ]
 [ 1421548.8  1600000. ]
 [  613645.7   650000. ]
 [  600001.4   600000. ]
 [ 1165426.7   850000. ]
 [ 1200011.7  1200000. ]
 [  699999.8   700000. ]
 [ 2578008.5  2200000. ]]


In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_hat))

0.26670710580768286


In [ ]:
print(r2_score(y_train,lr.predict(xtrain_poly)))

1.0
